FROM apache/airflow:2.8.1

USER root
# Install Java for PySpark
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         openjdk-17-jre-headless \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
# Install dependencies for Lakehouse pipeline
RUN pip install --no-cache-dir "apache-airflow==2.8.1" dbt-postgres pyspark loguru pyarrow
